version: '3'
services:
   routeservice:
      container_name: ors-app
      ports:
         - 8080:8080
      image: "benbergstein/open-route-service:SanFrancisco"
      volumes:
         - ./data/graphs:/ors-core/data/graphs
         - ./data/elevation_cache:/ors-core/data/elevation_cache
         - ./data/logs/ors/:/var/log/ors/
         - ./data/logs/tomcat/:/usr/local/tomcat/logs
      environment:
         - JAVA_OPTS=-Djava.awt.headless=true -server -XX:TargetSurvivorRatio=75 -XX:SurvivorRatio=64 -XX:MaxTenuringThreshold=3 -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:ParallelGCThreads=4 -Xms1g -Xmx20g
         - CATALINA_OPTS= -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9001 -Dcom.sun.management.jmxremote.rmi.port=9001 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost

   client:
      image: benbergstein/route-web:latest
      environment:
         - REACT_APP_TILE_SERVICE_KEY=${TILE_SERVICE_KEY}
      ports:
         - 3000:3000
      volumes:
         - .:/app
