version: '3.7'
services:
   haproxy:
      image: haproxy:1.7
      volumes:
         - ./deploy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
         - ${DATA_DIR:-./data}/letsencrypt:/etc/letsencrypt
      networks:
         - routeplanner-deploy
         - haproxy-controller_haproxy-controller
      ports:
         - "8081:8081"


   routeservice:
      image: benbergstein/open-route-service:BayArea
      volumes:
         - ${DATA_DIR:-./data}/graphs:/ors-core/data/graphs
         - ${DATA_DIR:-./data}/elevation_cache:/ors-core/data/elevation_cache
         - ${DATA_DIR:-./data}/logs/ors/:/var/log/ors/
         - ${DATA_DIR:-./data}/logs/tomcat/:/usr/local/tomcat/logs
      environment:
         - JAVA_OPTS=-Djava.awt.headless=true -server -XX:TargetSurvivorRatio=75 -XX:SurvivorRatio=64 -XX:MaxTenuringThreshold=3 -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:ParallelGCThreads=4 -Xms1g -Xmx20g
         - CATALINA_OPTS= -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9001 -Dcom.sun.management.jmxremote.rmi.port=9001 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost
      networks:
         - routeplanner-deploy
         - haproxy-controller_haproxy-controller

   app:
      image: benbergstein/route-web:latest
      env_file: ./deploy/.env
      environment:
         - REACT_APP_TILE_SERVICE_KEY=${TILE_SERVICE_KEY}
         - REACT_APP_ROUTING_HOST
         - REACT_APP_HTTPS
      networks:
         - routeplanner-deploy
         - haproxy-controller_haproxy-controller

networks:
   routeplanner-deploy:
   haproxy-controller_haproxy-controller:
      external: true
